homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 60
  # metric for Metric, imperial for Imperial
  unit_system: metric
  time_zone: !secret time_zone
  # Customization file
  customize: !include_dir_merge_named config/customize
  packages: !include_dir_merge_named config/packages

# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:
# Enables the frontend
frontend:

# Enables configuration UI
config:


# Discover some devices automatically
discovery:
  ignore:
    - apple_tv

# Show the introduction message on startup.
#introduction:

ios:

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: !secret tuya_country_code

#Run some python scripts
python_script:


stream:


recorder:
  purge_interval: 2
  purge_keep_days: 30
  db_url: !secret mariadb_connection_url

influxdb:
  host: !secret docker_host
  include:
    domains:
      - sensor

#System Health
system_health:

# Enables support for tracking state changes over time
history:

logbook:
# Enables a map showing the location of tracked devices
map:

#imbed stuff
panel_iframe:
  tasmoadmin:
    title: 'TasmoAdmin'
    url: 'http://192.168.19.6:9999'
    icon: mdi:home-automation

#Ring doorbell
ring:
  username: !secret ring_username
  password: !secret ring_password

  

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#http:
#   base_url: example.duckdns.org:8123

# Sensors
#sensor:
  # Weather prediction
#  - platform: yr

# Text to speech
tts:
  - platform: google

mqtt:
   broker: !secret docker_host
   port: 1883
   client_id: home-assistant-1
   keepalive: 60
   username: !secret mqtt_User
   password: !secret mqtt_Pass
   protocol: 3.1
   birth_message:
     topic: "tele/hass1/LWT"
     payload: "Online"
     qos: 1
     retain: true
   will_message:
     topic: "tele/hass1/LWT"
     payload: "Offline"
     qos: 1
     retain: true
#GUI

lovelace:
  mode: yaml

#components
automation: !include_dir_merge_list config/automation
binary_sensor: !include_dir_merge_list config/binary_sensor
climate: !include_dir_merge_list config/climate
group: !include_dir_merge_named config/group
input_boolean: !include_dir_merge_named config/input_boolean
light: !include_dir_merge_list config/light
media_player: !include_dir_merge_list config/media_player
scene: !include_dir_merge_list config/scene
script: !include_dir_merge_named config/script
sensor: !include_dir_merge_list config/sensor
switch: !include_dir_merge_list config/switch
weather: !include_dir_merge_list config/weather


