# Bedroom 1 TV
- platform: mqtt
  name: Master Bedroom TV
  state_topic: "stat/SW-K1/POWER"
  command_topic: "cmnd/SW-K1/POWER"
  availability_topic: "tele/SW-K1/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"