# Arlec 433Mhz switches

-  platform: mqtt
   name: “Kitchen water feature”
   state_topic: “home/Power_A”
   command_topic: “home/Power_A”

-  platform: mqtt
   name: “Kitchen TV”
   state_topic: “home/Power_B”
   command_topic: “home/Power_B”


-  platform: mqtt
   name: “Switch C”
   state_topic: “home/Power_C”
   command_topic: “home/Power_C”