# Computer Room Spare
- platform: mqtt
  name: Computer Room Spare
  state_topic: "stat/sonoffs20-2/POWER"
  command_topic: "cmnd/sonoffs20-2/POWER"
  availability_topic: "tele/sonoffs20-2/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"