# Washing Machine
- platform: mqtt
  name: Washer Power
  state_topic: "stat/sonoffpow4/POWER"
  command_topic: "cmnd/sonoffpow4/POWER"
  availability_topic: "tele/sonoffpow4/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
