# Arlec 433Mhz switches

-  platform: mqtt
   name: “Kitchen water feature”
   state_topic: “sonoffbr/tele/RESULT”
   command_topic: “sonoffbr/cmnd/RfCode”
   qos: 1
   payload_on: “#86CC0F”
   payload_off: “#86CC0E”
   retain: true

-  platform: mqtt
   name: “Switch C”
   state_topic: “sonoffbr/tele/RESULT”
   command_topic: “sonoffbr/cmnd/RfCode”
   availability_topic: "sonoffbr/tele/LWT"
   qos: 1
   payload_on: “#86CC0B”
   payload_off: “#86CC0A”
   payload_available: "Online"
   payload_not_available: "Offline"
   optimistic: true