# Bedroom 1 Lamp
- platform: mqtt
  name: Bedroom 1 lamp
  state_topic: "stat/sonoffs20-3/POWER"
  command_topic: "cmnd/sonoffs20-3/POWER"
  availability_topic: "tele/sonoffs20-3/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"