# Bedroom 2
#- platform: mqtt
#  name: Bedroom 2 Bedhead
#  state_topic: "stat/sonoffK-3/POWER"
#  command_topic: "cmnd/sonoffK-3/POWER"
#  availability_topic: "tele/sonoffK-3/LWT"
#  qos: 1
#  payload_on: "ON"
#  payload_off: "OFF"
#  payload_available: "Online"
#  payload_not_available: "Offline"