- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: swap_use_percent
    - type: last_boot
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0



# $  cat /sys/devices/virtual/thermal/thermal_zone?/temp lists 4 thermal zones
# on a LENOVO 20324/IdeaPad Flex10, BIOS 93CN54WW 10/09/2014 
#CPU0: Intel(R) Pentium(R) CPU  N3530  @ 2.16GHz 

# This version should work on both stand alone and docker installs

- platform: command_line
  name: Core0 Temp
  command: "cat /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp2_input"
  unit_of_measurement: "째C"
  value_template: '{{ value | multiply(0.001) }}'

- platform: command_line
  name: Core1 Temp
  command: "cat /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp3_input"
  unit_of_measurement: "째C"
  value_template: '{{ value | multiply(0.001) }}'

- platform: command_line
  name: Core2 Temp
  command: "cat /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp4_input"
  unit_of_measurement: "째C"
  value_template: '{{ value | multiply(0.001) }}'

- platform: command_line
  name: Core3 Temp
  command: "cat /sys/devices/platform/coretemp.0/hwmon/hwmon0/temp5_input"
  unit_of_measurement: "째C"
  value_template: '{{ value | multiply(0.001) }}'

- platform: cpuspeed
- platform: linux_battery

