Office:
  name: Office
  icon: mdi:office-building
  entities:
    - input_boolean.rf_switch2_switch
    - switch.office_computer
    - sensor.office_computer
    - sensor.computer_watts
    - switch.office_peripherals
    - sensor.office_peripherals
    - sensor.peripherals_watts
    - media_player.office_tv
    - media_player.jbllinkview8082
    - cover.office_window
    - light.23006027cc50e349ff8b
    